package main
import("crypto/sha256";"encoding/hex";"encoding/json";"fmt";"os";"sort";"strings")
const kitPath="passport-conformance-kit-v342/ENTITY_V3_4_2_GLOBAL_PASSPORT_CLEANROOM_KIT.min.json"
const kitSHA="ced70113f1d153627eb972b11adbf20e502ed086e0b13e8abf1dc5adc4c2e716"
const expected="45af773554a7191c1b49a75c636a1106afb1de36d788bb00d7af56097b8d1b0e"
var core=[]string{"ENTITY","AUTHORITY","RIGHT","EVENT","VALUE"}
func sha(b []byte)string{h:=sha256.Sum256(b);return hex.EncodeToString(h[:])}
func s(r map[string]any,k string)string{v,_:=r[k].(string);return v}
func b(r map[string]any,k string,w bool)bool{v,ok:=r[k].(bool);return ok&&v==w}
func hex64(v any)bool{x,ok:=v.(string);if !ok||len(x)!=64{return false};for _,c:=range x{if !(c>='0'&&c<='9'||c>='a'&&c<='f'){return false}};return true}
func strArr(v any)([]string,bool){a,ok:=v.([]any);if !ok{return nil,false};o:=make([]string,len(a));for i,x:=range a{q,ok:=x.(string);if !ok{return nil,false};o[i]=q};return o,true}
func arrEq(v any,w []string)bool{a,ok:=strArr(v);if !ok||len(a)!=len(w){return false};for i:=range w{if a[i]!=w[i]{return false}};return true}
func btdu(r map[string]any)bool{return s(r,"schema")=="entity-btdu-passport-binding-v1"&&s(r,"btdu_version")=="3.4.2"&&s(r,"universe_root")!=""&&s(r,"object_ref")!=""&&hex64(r["content_sha256"])&&s(r,"sovereign_entity_id")!=""&&b(r,"protocol_origin_is_not_asset_provenance",true)&&b(r,"topology_does_not_create_ownership",true)&&b(r,"topology_does_not_create_economic_entitlement",true)&&r["automatic_protocol_royalty_bps"]==float64(0)}
func stack(r map[string]any)bool{refs,ok:=strArr(r["profile_refs"]);if !ok||len(refs)==0{return false};global:=false;for _,x:=range refs{if x=="entity-profile:global@1.0"{global=true}};hs,ok:=r["profile_hashes"].([]any);if !ok||len(hs)!=len(refs){return false};for _,h:=range hs{if !hex64(h){return false}};return global&&b(r,"fail_closed",true)&&b(r,"profile_composition_does_not_create_authority",true)&&b(r,"standards_mapping_is_not_normative_equivalence",true)}
func valid(r map[string]any)bool{switch s(r,"schema"){
case "entity-v3-global-passport-profile-status-v1":return arrEq(r["core_primitives"],core)&&b(r,"core_semantics_changed",false)&&b(r,"market_engine_preserved",true)&&b(r,"one_passport_many_profiles",true)&&b(r,"evidence_truth_boundary_preserved",true)
case "entity-v3-global-profile-v1": k:=s(r,"kind");allowed:=map[string]bool{"GLOBAL":true,"JURISDICTION":true,"INDUSTRY":true,"DOMAIN":true,"PRIVACY":true,"TRUST":true,"DISCLOSURE":true};return s(r,"profile_ref")!=""&&allowed[k]&&hex64(r["schema_sha256"])&&b(r,"profile_is_not_authority",true)&&b(r,"standards_mapping_is_not_normative_equivalence",true)&&(!strings.Contains(strings.ToUpper(s(r,"profile_id")),"DEFENCE")||b(r,"public_unclassified",true))
case "entity-v3-profile-stack-resolution-v1":return stack(r)
case "entity-v3-global-passport-v1": ps,ok:=r["profile_stack"].(map[string]any);if !ok{return false};if x,exists:=r["btdu_binding"];exists&&x!=nil{q,ok:=x.(map[string]any);if !ok||!btdu(q){return false}};e,ok:=r["economic_state"].(map[string]any);if !ok{return false};amount,ok:=e["amount_units"].(float64);if !ok||amount<0{return false};maps,ok:=r["standards_mappings"].([]any);if !ok{return false};for _,x:=range maps{m,ok:=x.(map[string]any);if !ok||!b(m,"normative_equivalence_claimed",false){return false}};return arrEq(r["core_primitives"],core)&&s(r,"rights_passport_id")!=""&&hex64(r["rights_passport_sha256"])&&stack(ps)&&b(r,"one_passport_many_profiles",true)&&b(r,"profile_composition_does_not_create_authority",true)&&b(r,"standards_mapping_is_not_normative_equivalence",true)&&b(r,"evidence_does_not_establish_objective_truth",true)&&b(r,"legal_effect_is_deployment_specific",true)&&b(r,"underlying_information_remains_nonrival",true)&&b(e,"market_observation_is_not_accounting_fair_value",true)
case "entity-v3-continuous-ingest-result-v1":n,ok:=r["files"].(float64);return ok&&n>=0&&hex64(r["inventory_sha256"])&&b(r,"content_addressed",true)&&b(r,"custody_is_not_authority",true)&&b(r,"economic_value_invented",false)};return false}
func canonical(v any)string{switch x:=v.(type){case map[string]any:ks:=make([]string,0,len(x));for k:=range x{ks=append(ks,k)};sort.Strings(ks);parts:=make([]string,len(ks));for i,k:=range ks{kb,_:=json.Marshal(k);parts[i]=string(kb)+":"+canonical(x[k])};return "{"+strings.Join(parts,",")+"}";case []any:parts:=make([]string,len(x));for i,q:=range x{parts[i]=canonical(q)};return "["+strings.Join(parts,",")+"]";default:b,_:=json.Marshal(v);return string(b)}}
func main(){raw,err:=os.ReadFile(kitPath);if err!=nil{panic(err)};if sha(raw)!=kitSHA{panic("sealed kit SHA-256 mismatch")};var kit map[string]any;if err=json.Unmarshal(raw,&kit);err!=nil{panic(err)};cases:=kit["cases"].([]any);sort.Slice(cases,func(i,j int)bool{return s(cases[i].(map[string]any),"id")<s(cases[j].(map[string]any),"id")});rows:=[]any{};passed:=0;for _,q:=range cases{c:=q.(map[string]any);actual:="INVALID";if valid(c["record"].(map[string]any)){actual="VALID"};if actual==s(c,"expect"){passed++};rows=append(rows,map[string]any{"id":s(c,"id"),"actual":actual})};result:=sha([]byte(canonical(rows)));overall:=passed==26&&result==expected&&s(kit,"expected_result_sha256")==expected;out:=map[string]any{"implementation":"go","kit_sha256":kitSHA,"vectors_passed":passed,"vectors_total":26,"result_sha256":result,"expected_result_sha256":expected,"overall_valid":overall};enc,_:=json.MarshalIndent(out,"","  ");fmt.Println(string(enc));if !overall{os.Exit(1)}}
