package main
import("crypto/sha256";"encoding/hex";"encoding/json";"fmt";"os";"path/filepath";"strconv";"strings")
type M map[string]any
func load(p string)M{b,e:=os.ReadFile(p);if e!=nil{panic(e)};var v M;if e=json.Unmarshal(b,&v);e!=nil{panic(e)};return v}
func m(v any)M{x,_:=v.(map[string]any);return x};func s(v any)string{x,_:=v.(string);return x};func n(v any)int64{x,_:=v.(float64);return int64(x)};func sha(t string)string{h:=sha256.Sum256([]byte(t));return hex.EncodeToString(h[:])}
func canon(x M)string{p:=m(x["primitives"]);mk:=m(x["market"]);d:=m(x["declared"]);ev:=[]string{};for _,z:=range p["events"].([]any){ev=append(ev,s(m(z)["type"]))};return strings.Join([]string{s(x["version"]),s(m(p["entity"])["id"]),s(m(p["authority"])["id"]),s(m(p["right"])["id"]),s(mk["instrument_id"]),s(mk["venue_id"]),s(mk["seller_entity_id"]),s(mk["buyer_entity_id"]),strconv.FormatInt(n(mk["quantity"]),10),strconv.FormatInt(n(mk["unit_price_minor"]),10),strconv.FormatInt(n(mk["originator_bps"]),10),s(mk["usage_action"]),strconv.FormatInt(n(d["gross_minor"]),10),strconv.FormatInt(n(d["originator_minor"]),10),strconv.FormatInt(n(d["seller_net_minor"]),10),strings.Join(ev,",")},"|")}
func valid(x M)bool{if s(x["schema"])!="entity-v3-polyglot-transaction-v1"||s(x["version"])!="3.0.0"{return false};p:=m(x["primitives"]);mk:=m(x["market"]);d:=m(x["declared"]);a:=m(p["authority"]);r:=m(p["right"]);e:=m(p["entity"]);if s(a["principal_entity_id"])!=s(mk["seller_entity_id"])||s(r["grantor_entity_id"])!=s(mk["seller_entity_id"])||s(r["subject_entity_id"])!=s(e["id"]){return false};q,pr,bps:=n(mk["quantity"]),n(mk["unit_price_minor"]),n(mk["originator_bps"]);if q<=0||pr<0||bps<0||bps>10000||s(mk["buyer_entity_id"])==s(mk["seller_entity_id"]){return false};allow:=false;for _,z:=range r["actions"].([]any){if s(z)==s(mk["usage_action"]){allow=true}};if !allow{return false};ex:=[]string{"REGISTER","DELEGATE","GRANT_RIGHT","LIST","TRADE","SETTLE","ENTITLE","USE","VALUE"};ev:=p["events"].([]any);if len(ev)!=len(ex){return false};for i,z:=range ev{zz:=m(z);if s(zz["type"])!=ex[i]||n(zz["seq"])!=int64(i+1){return false}};g:=q*pr;o:=g*bps/10000;if n(d["gross_minor"])!=g||n(d["originator_minor"])!=o||n(d["seller_net_minor"])!=g-o{return false};return sha(canon(x))==s(x["state_root_sha256"])}
func main(){repo,_:=os.Getwd();kit:=filepath.Join(repo,"conformance-kit");good:=load(filepath.Join(kit,"VALID_TRANSACTION.json"));man:=load(filepath.Join(kit,"CONFORMANCE_MANIFEST.json"));rec:=load(filepath.Join(kit,"RECOVERY_EXPORT.json"));exp:=load(filepath.Join(kit,"EXPECTED_RESULT.json"));rej:=0;for _,z:=range man["invalid_vectors"].([]any){if !valid(load(filepath.Join(kit,s(z)))){rej++}};cs:=[]string{};for _,z:=range rec["controller_entities"].([]any){cs=append(cs,s(z))};rr:=sha(strings.Join([]string{s(rec["version"]),s(rec["state_root_sha256"]),strings.Join(cs,","),strconv.FormatInt(n(rec["recovery_epoch"]),10)},"|"));result:=sha(strings.Join([]string{s(good["state_root_sha256"]),s(rec["recovery_root_sha256"]),strconv.Itoa(rej)},"|"));pass:=valid(good)&&rr==s(rec["recovery_root_sha256"])&&s(rec["state_root_sha256"])==s(good["state_root_sha256"])&&rej==len(man["invalid_vectors"].([]any))&&result==s(exp["result_sha256"]);out:=M{"implementation":"go","pass":pass,"state_root_sha256":good["state_root_sha256"],"recovery_root_sha256":rec["recovery_root_sha256"],"invalid_vectors_rejected":rej,"result_sha256":result};os.MkdirAll(filepath.Join(repo,"qualification"),0755);raw,_:=json.MarshalIndent(out,"","  ");os.WriteFile(filepath.Join(repo,"qualification","result.json"),raw,0644);fmt.Println(string(raw));if !pass{os.Exit(2)}}

